# ══════════════════════════════════════════════════════════════════════════════
# PROJECT METADATA
# ══════════════════════════════════════════════════════════════════════════════
[project]
name = "zipr"
version = "0.1.0"
description = "zip, but it actually uses all your cores."
readme = "README.md"
authors = [
    { name = "fstormacq", email = "florian_stormacq@icloud.com" }
]
requires-python = ">=3.14"
dependencies = []

# ══════════════════════════════════════════════════════════════════════════════
# PROJECT SCRIPTS
# ══════════════════════════════════════════════════════════════════════════════
[project.scripts]
zipr = "src.main:main"


# ══════════════════════════════════════════════════════════════════════════════
# BUILD SYSTEM
# ══════════════════════════════════════════════════════════════════════════════
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# ══════════════════════════════════════════════════════════════════════════════
# HATCH
# ══════════════════════════════════════════════════════════════════════════════
[tool.hatch.build.targets.wheel]
packages = ["src"]